### ISSUE TITLE
Stats may not be collected if HTTP::Status does not recognise the status code

### ISSUE THREAD

**Issue by robrwo** [robrwo/Plack-Middleware-Statsd#2]
HTTP::Server::PSGI uses HTTP::Status to get the status message. When the status message is undefined, the metrics do not appear to be logged.

Note that the issue can be fixed by upgrading HTTP::Message to v6.16, if the status code conforms to the list of standard codes.

If you are sending non-standard codes, then this may be an issue.

**Comment by robrwo** [comment]
When HTTP stats PRs https://github.com/libwww-perl/HTTP-Message/pull/104 and https://github.com/libwww-perl/HTTP-Message/pull/106 are merged and release, we can increment the minimum recommended version of HTTP::Status accordingly.

**Comment by vanHoesel** [comment]
HTTP::Status 6.16. is broken

**Comment by robrwo** [comment]
This seems to be an issue with Net::Server or Plack, not this module. it's documented.
